name: my_env2
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2024.2.2=h56e8100_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cuda=12.4.1=0
  - cuda-cccl=12.4.127=0
  - cuda-command-line-tools=12.4.1=0
  - cuda-compiler=12.4.1=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cuobjdump=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-cuxxfilt=12.4.127=0
  - cuda-demo-suite=12.4.127=0
  - cuda-documentation=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=0
  - cuda-nsight-compute=12.4.1=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=12.4.127=0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=12.4.127=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-nvvp=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-opencl-dev=12.4.127=0
  - cuda-profiler-api=12.4.127=0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=12.4.1=0
  - cuda-tools=12.4.1=0
  - cuda-visual-tools=12.4.1=0
  - cudatoolkit=11.2.0=h608a323_8
  - cudnn=8.1.0.77=h3e0f4f4_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - eigen=3.4.0=h91493d7_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_h38027f0_108
  - hdf5=1.14.3=nompi_h73e8ff5_100
  - intel-openmp=2024.1.0=h57928b3_965
  - ipython=8.18.1=pyh7428d3b_3
  - ipywidgets=8.1.2=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.10=pyhd8ed1ab_0
  - krb5=1.21.2=heb0366b_0
  - lerc=4.0.0=h63175ca_0
  - libaec=1.1.3=h63175ca_0
  - libblas=3.9.0=22_win64_mkl
  - libcblas=3.9.0=22_win64_mkl
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.7.1=hd5e4a3a_0
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libdeflate=1.20=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libhwloc=2.10.0=default_h2fffb23_1000
  - libiconv=1.17=hcfcfb64_2
  - libitk=5.3.0=h170c4af_8
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=22_win64_mkl
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=12.4.127=0
  - libnvfatbin-dev=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libsqlite=3.45.3=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libtiff=4.6.0=hddb2be6_3
  - libxml2=2.12.6=hc3477c8_2
  - libzlib=1.2.13=hcfcfb64_5
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2024.1.0=h66d3029_692
  - nsight-compute=2024.1.1.4=0
  - numpy=1.26.4=py39hddb5d58_0
  - openssl=3.3.0=hcfcfb64_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.9.19=h4de0772_0_cpython
  - python_abi=3.9=4_cp39
  - scikit-learn=1.4.2=py39h7c199eb_0
  - scipy=1.13.0=py39h1a10956_1
  - setuptools=69.5.1=pyhd8ed1ab_0
  - simpleitk=2.3.1=py39h99910a6_2
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.12.0=h91493d7_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h5226925_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.10=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - zstd=1.5.5=h12be248_0
  - pip:
      - absl-py==1.4.0
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-record==0.4.1
      - arrow==1.3.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - defusedxml==0.7.1
      - dm-tree==0.1.8
      - etils==1.5.2
      - fastjsonschema==2.19.1
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - fqdn==1.5.1
      - fsspec==2024.3.1
      - gast==0.4.0
      - google-auth==2.29.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - googleapis-common-protos==1.63.0
      - grpcio==1.62.2
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - ipykernel==6.29.4
      - isoduration==20.11.0
      - jinja2==3.1.3
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.1
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.1.3
      - notebook-shim==0.2.4
      - nvidia-ml-py3==7.352.0
      - oauthlib==3.2.2
      - openexr==3.2.4
      - opt-einsum==3.3.0
      - overrides==7.7.0
      - packaging==24.0
      - pandocfilters==1.5.1
      - pillow==10.3.0
      - platformdirs==4.2.1
      - prometheus-client==0.20.0
      - promise==2.3
      - protobuf==3.19.6
      - psutil==5.9.8
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pywin32==306
      - pywinpty==2.0.13
      - pyyaml==6.0.1
      - pyzmq==26.0.2
      - referencing==0.35.0
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - rsa==4.9
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.5
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-addons==0.22.0
      - tensorflow-datasets==4.9.0
      - tensorflow-estimator==2.10.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorflow-metadata==1.13.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - tinycss2==1.3.0
      - toml==0.10.2
      - tomli==2.0.1
      - tornado==6.4
      - tqdm==4.66.2
      - trimesh==4.3.1
      - typeguard==2.13.3
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - urllib3==2.2.1
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.2
      - wrapt==1.16.0
      - zipp==3.18.1
